spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Airline
    username: root
    password: root

  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
