spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Airline
    username: root
    password: root

#  thymeleaf:
#    prefix: classpath:/template/
#    suffix: .html

  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
