spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Airline
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: ossairline@gmail.com
    password: evkr ttjf axxu yefn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

server:
  servlet:
    session:
      timeout: 30m
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    org:
      springframework:
        mail: DEBUG

